version: 2
jobs:
  build:
    docker:
      - image: ocaml/opam:debian-9_ocaml-4.06.0_flambda

    steps:
      - checkout

      - run:
          name: make
          command: opam update && opam install dune && make && make install

      - run:
          name: run bondi
          command: bondi